services:
  - type: web
    name: groweasy-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
      - key: GROQ_API_KEY
        sync: false
      - key: LLM_MODEL
        value: llama-3.3-70b-versatile
